### ISSUE TITLE
Can't sort on key path type array

### ISSUE THREAD

**Issue by ClumsySmurf** [realm/realm-studio#1158]
Sentry ID: 1f4f3d2dc8484352b8ae2a87c231922e

Error: Cannot sort on key path 'runtimeData': property 'Test.runtimeData' is of unsupported type 'array'.
    at ve.filteredSortedResults.d (file:///Applications/Realm%20Studio.app/Contents/Resources/app.asar/build/realm-browser.renderer.bundle.js:1:51577)
    at ve.result [as filteredSortedResults] (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/memoize-one/lib/index.js:31:27)
    at ve.getProps (file:///Applications/Realm%20Studio.app/Contents/Resources/app.asar/build/realm-browser.renderer.bundle.js:1:58478)
    at ve.render (file:///Applications/Realm%20Studio.app/Contents/Resources/app.asar/build/realm-browser.renderer.bundle.js:1:58314)
    at finishClassComponent (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13085:31)
    at updateClassComponent (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13047:10)
    at beginWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13715:14)
    at performUnitOfWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15741:12)
    at workLoop (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15780:24)
    at renderRoot (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15820:7)
    at performWorkOnRoot (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16437:22)
    at performWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16358:7)
    at performSyncWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16330:3)
    at interactiveUpdates$1 (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16597:7)
    at interactiveUpdates (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:2150:10)
    at dispatchInteractiveEvent (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:4528:3)
    at HTMLDocument.wrapped (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/@sentry/electron/node_modules/@sentry/browser/dist/index.js:2471:21)
    in ve (created by Ke)
    in div (created by Ke)
    in div (created by Ke)
    in Ke (created by Ue)
    in Ue (created by _)
    in _
    in w

**Comment by bmunkholm** [comment]
@ClumsySmurf How can this be reproduced?

**Comment by ClumsySmurf** [comment]
It’s been awhile. I believe I had an object which had a relationship to an array and I was trying to use graphql to search in realm studio and it crashed.

**Comment by steffenagger** [comment]
Closing this due to inactivity.
Please open a new issue, if the problem still occurs.
