### ISSUE TITLE
[add title here] (Sentry ID: a7c05040bcec4dadb86786f7911c6991)

### ISSUE THREAD

**Issue by mizbandev** [realm/realm-studio#1269]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Versions:**
 - OS: [e.g. Mac/Windows/]
 - Studio Version [e.g. 2.0.0]
 - Realm Object Server version [e.g. 3.0.1]

**Additional context**

**Comment by mizbandev** [comment]
Error: Cannot sort on key path '��"': property 'default.��"' does not exist.
    at it.filteredSortedResults.E (file:///C:/Program%20Files/Realm%20Studio/resources/app.asar/build/realm-browser.renderer.bundle.js:1:64910)
    at it.memoized [as filteredSortedResults] (C:\Program Files\Realm Studio\resources\app.asar\node_modules\memoize-one\dist\memoize-one.cjs.js:29:31)
    at it.getProps (file:///C:/Program%20Files/Realm%20Studio/resources/app.asar/build/realm-browser.renderer.bundle.js:1:72434)
    at it.render (file:///C:/Program%20Files/Realm%20Studio/resources/app.asar/build/realm-browser.renderer.bundle.js:1:72245)
    at finishClassComponent (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17184:31)
    at updateClassComponent (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17134:24)
    at beginWork (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:18653:16)
    at HTMLUnknownElement.callCallback (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:188:14)
    at HTMLUnknownElement.sentryWrapped (C:\Program Files\Realm Studio\resources\app.asar\node_modules\@sentry\browser\dist\index.js:3204:27)
    at Object.invokeGuardedCallbackDev (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:237:16)
    at invokeGuardedCallback (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:292:31)
    at beginWork$1 (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23234:7)
    at performUnitOfWork (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22188:12)
    at workLoopSync (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22161:22)
    at performSyncWorkOnRoot (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21787:9)
    at C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11111:24
    at unstable_runWithPriority (C:\Program Files\Realm Studio\resources\app.asar\node_modules\scheduler\cjs\scheduler.development.js:653:12)
    at runWithPriority$1 (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11061:10)
    at flushSyncCallbackQueueImpl (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11106:7)
    at flushSyncCallbackQueue (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11094:3)
    at discreteUpdates$1 (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21924:7)
    at discreteUpdates (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1071:12)
    at dispatchDiscreteEvent (C:\Program Files\Realm Studio\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4168:3)
    at HTMLDocument.sentryWrapped (C:\Program Files\Realm Studio\resources\app.asar\node_modules\@sentry\browser\dist\index.js:3204:27)
    in it (created by St)
    in div (created by St)
    in div (created by St)
    in St (created by Et)
    in Et (created by I)
    in I
    in y

**Comment by kraenhansen** [comment]
Would it be possible to share the Realm database file you are working on?

**Comment by kraenhansen** [comment]
Closing this - please reopen if you decide to share the database file.
