### ISSUE TITLE
Cannot open Synced Realm: "Nonupgradable history schema" (Sentry ID: 6c161f5474dd47528f01c51fe7029f34)

### ISSUE THREAD

**Issue by cferg-entale** [realm/realm-studio#1319]
**Describe the bug**
I cannot open a Realm Cloud using Realm Studio 3.11.0. After selecting the Realm Cloud instance from the list I get "Realm Studio encountered an unrecoverable error! ID: “6c161f5474dd47528f01c51fe7029f34”" with this stacktrace:
```
Incompatible histories. Nonupgradable history schema Path:Exception backtrace:
0   .io.realm.realm-studio.qZxgM5       0x00000001134436d4 _ZN5realm21IncompatibleHistoriesC1ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_ + 84
1   .io.realm.realm-studio.qZxgM5       0x0000000113441f6e _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 7166
2   .io.realm.realm-studio.qZxgM5       0x0000000113444353 _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 243
3   .io.realm.realm-studio.qZxgM5       0x0000000113448f4b _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 347
4   .io.realm.realm-studio.qZxgM5       0x00000001130865f5 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 1277
5   .io.realm.realm-studio.qZxgM5       0x0000000113085660 _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 62
6   .io.realm.realm-studio.qZxgM5       0x00000001130854ec _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 202
7   .io.realm.realm-studio.qZxgM5       0x000000011306ed90 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 128
8   .io.realm.realm-studio.qZxgM5       0x0000000112f67e32 _ZN5realm2js10RealmClassINS_4node5TypesEE19create_shared_realmEN4Napi3EnvENS_5Realm6ConfigEbONSt3__13mapINS9_12basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEENSA_ISG_NS0_9ProtectedINS5_5ValueEEENS9_4lessISG_EENSE_INS9_4pairIKSG_SJ_EEEEEESL_NSE_INSM_ISN_SQ_EEEEEEONSA_ISG_NSH_INS5_8FunctionEEESL_NSE_INSM_ISN_SW_EEEEEE + 234
9   .io.realm.realm-studio.qZxgM5       0x0000000112f66609 _ZN5realm2js10RealmClassINS_4node5TypesEE11constructorEN4Napi3EnvENS5_6ObjectERNS0_9ArgumentsIS3_EE + 331
10  .io.realm.realm-studio.qZxgM5       0x0000000112f62ddb _ZN5realm4node10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE20constructor_callbackERKN4Napi12CallbackInfoE + 135
11  .io.realm.realm-studio.qZxgM5       0x0000000112f655d8 _ZN5realm4node13WrappedObjectINS_2js10RealmClassINS0_5TypesEEEEC2ERKN4Napi12CallbackInfoE + 128
12  .io.realm.realm-studio.qZxgM5       0x0000000112f654ad _ZZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE26ConstructorCallbackWrapperEP10napi_env__P20napi_callback_info__ENKUlvE_clEv + 67
13  .io.realm.realm-studio.qZxgM5       0x0000000112f65223 _ZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE26ConstructorCallbackWrapperEP10napi_env__P20napi_callback_info__ + 71
14  Electron Framework                  0x000000010f36e63a napi_create_function + 858
15  Electron Framework                  0x000000010a820cec _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 16844
16  Electron Framework                  0x000000010a81feb8 _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 13208
17  Electron Framework                  0x000000010a81f79f _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 11391
18  Electron Framework                  0x000000010b222b59 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 501145
19  Electron Framework                  0x000000010b1ae2c1 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 23809.
    at RealmProvider.<anonymous> (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-realm-context/build/RealmProvider.js:49:31)
    at RealmProvider.memoized [as memoizedRealm] (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/memoize-one/dist/memoize-one.cjs.js:29:31)
    at RealmProvider.render (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-realm-context/build/RealmProvider.js:70:32)
    at finishClassComponent (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17160:31)
    at updateClassComponent (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17110:24)
    at beginWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18620:16)
    at HTMLUnknownElement.callCallback (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at HTMLUnknownElement.sentryWrapped (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/@sentry/browser/dist/helpers.js:74:23)
    at Object.invokeGuardedCallbackDev (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:237:16)
    at invokeGuardedCallback (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:292:31)
    at beginWork$1 (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
    at performUnitOfWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22157:12)
    at workLoopSync (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22130:22)
    at performSyncWorkOnRoot (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21756:9)
    at /Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11089:24
    at unstable_runWithPriority (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority$1 (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11039:10)
    at flushSyncCallbackQueueImpl (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11084:7)
    at flushSyncCallbackQueue (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11072:3)
    at scheduleUpdateOnFiber (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21199:9)
    at Object.enqueueSetState (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12639:5)
    at Et.Component.setState (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:471:16)
    at Et.authenticate (file:///Applications/Realm%20Studio.app/Contents/Resources/app.asar/build/server-administration.renderer.bundle.js:1:76541)
    at async Et.componentDidMount (file:///Applications/Realm%20Studio.app/Contents/Resources/app.asar/build/server-administration.renderer.bundle.js:1:72891)
    in RealmProvider (created by Et)
    in Et (created by I)
    in I
    in y
```
**Versions:**
 - OS: MacOS 10.15.5
 - Studio Version: 3.11.0
 - Realm Object Server version: 3.4.2

**Comment by cferg-entale** [comment]
Has there been any movement on this issue?

**Comment by ianpward** [comment]
@cferg-entale Can you try clearing your local cache and reconnecting? I believe it is under Help>Clear Local State

**Comment by cferg-entale** [comment]
@ianpward, thank you that has worked. I really appreciate it. Is that documented anywhere?
