### ISSUE TITLE
version 11 not work windows 10

### ISSUE THREAD

**Issue by Avatarchik** [realm/realm-studio#1420]
(node:8556) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[8556:0512/114422.639:INFO:CONSOLE(111)] "%cDownload the React DevTools for a better development experience: https://reactjs.org/link/react-devtools  
You might need to use a local HTTP server (instead of file://): https://reactjs.org/link/react-devtools-faq font-weight:bold", source: C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\@sentry\utils\dist\instrument.js (111)
[8556:0512/114422.741:INFO:CONSOLE(135)] "Uncaught Error: Could not locate the bindings file. Tried:
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\build\realm.node
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\build\Debug\realm.node
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\build\Release\realm.node
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\out\Debug\realm.node
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\Debug\realm.node
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\out\Release\realm.node
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\Release\realm.node
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\build\default\realm.node
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\compiled\12.18.3\win32\x64\realm.node
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\addon-build\release\install-root\realm.node
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\addon-build\debug\install-root\realm.node
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\addon-build\default\install-root\realm.node
 тЖТ C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\lib\binding\node-v85-win32-x64\realm.node", source: C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\bindings\bindings.js (135)
[8556:0512/114422.958:INFO:CONSOLE(111)] "Warning: Can't call %s on a component that is not yet mounted. This is a no-op, but it might indicate a bug 
in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the %s component.%s setState D
    at D (file:///C:/Program%20Files/MongoDB%20Realm%20Studio/resources/app.asar/build/greeting.renderer.bundle.js:1:124390)
    at div
    at Y (file:///C:/Program%20Files/MongoDB%20Realm%20Studio/resources/app.asar/build/greeting.renderer.bundle.js:1:129705)
    at W (file:///C:/Program%20Files/MongoDB%20Realm%20Studio/resources/app.asar/build/greeting.renderer.bundle.js:1:130744)
    at G (C:\Program Files\MongoDB Realm Studio\resources\app.asar\build\renderer.bundle.js:1:634402)
    at k (C:\Program Files\MongoDB Realm Studio\resources\app.asar\build\renderer.bundle.js:1:632973)", source: C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\@sentry\utils\dist\instrument.js (111)
[8556:0512/114422.984:INFO:CONSOLE(548)] "Refused to set unsafe header "user-agent"", source: C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\contentful\dist\contentful.node.js (548)
[8556:0512/114422.985:INFO:CONSOLE(548)] "Refused to set unsafe header "Accept-Encoding"", source: C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\contentful\dist\contentful.node.js (548)
Checking for update
[8556:0512/114423.393:VERBOSE1:CONSOLE(1)] "Main._createAppUI: 47.395751953125 ms", source: devtools://devtools/bundled/main/main.js (1)
[8556:0512/114423.441:VERBOSE1:CONSOLE(1)] "Main._showAppUI: 9.208984375 ms", source: devtools://devtools/bundled/main/main.js (1)
[8556:0512/114423.490:VERBOSE1:CONSOLE(1)] "Main._initializeTarget: 13.968994140625 ms", source: devtools://devtools/bundled/main/main.js (1)
[8556:0512/114423.758:VERBOSE1:CONSOLE(1)] "Main._lateInitialization: 0.539794921875 ms", source: devtools://devtools/bundled/main/main.js (1)        
Update for version 11.0.0-alpha.0 is not available (latest version: 11.0.0-alpha.0, downgrade is disallowed).

**Comment by kneth** [comment]
@Avatarchik Thank you for trying out v11.0.0-alpha.1. We are investigating some Windows issues with Studio v11.0.0-alpha.1 and JS v10.5.0-beta.1.

**Comment by kraenhansen** [comment]
A fix for this has been released as [MongoDB Realm Studio v11.0.0-beta.1](https://github.com/realm/realm-studio/releases/tag/v11.0.0-beta.1)
