### ISSUE TITLE
crashed after deleting rows (programatically) that were visible in Realm Studio

### ISSUE THREAD

**Issue by SogoGolf** [realm/realm-studio#921]
Sentry ID: e7b885045646426c9c50c0a0e445de68

Error: Accessing object of type Course which has been invalidated or deleted
    at ze.generateContentKey (file:///Applications/Realm%20Studio.app/Contents/Resources/app.asar/build/realm-browser.renderer.bundle.js:1:77330)
    at ze.render (file:///Applications/Realm%20Studio.app/Contents/Resources/app.asar/build/realm-browser.renderer.bundle.js:1:74307)
    at finishClassComponent (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13085:31)
    at updateClassComponent (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13047:10)
    at beginWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13715:14)
    at performUnitOfWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15741:12)
    at workLoop (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15780:24)
    at renderRoot (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15820:7)
    at performWorkOnRoot (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16437:22)
    at performWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16358:7)
    at performSyncWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16330:3)
    at requestWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16230:5)
    at scheduleWork$1 (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16096:11)
    at Object.enqueueSetState (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11185:5)
    at ze.Component.setState (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:273:16)
    at Realm.onRealmChanged (file:///Applications/Realm%20Studio.app/Contents/Resources/app.asar/build/realm-browser.renderer.bundle.js:1:69581)
    in ze (created by _)
    in _
    in w

**Comment by kraenhansen** [comment]
This was fixed in the 2.8.0 version of Realm Studio - please allow the app to automatically upgrade and reopen this issue if it (unexpectedly) persists.
