### ISSUE TITLE
Sorting array of numbers causes crash

### ISSUE THREAD

**Issue by amitv87** [realm/realm-studio#945]
Sentry ID: abb8e52a82bd48e68a023f05568b5460

```
Error: Cannot sort on key path 'ts': property 'ServerRideEventModel.ts' is of unsupported type 'array'.
    at Oe.filteredSortedResults.d (file:///Applications/Realm%20Studio.app/Contents/Resources/app.asar/build/realm-browser.renderer.bundle.js:1:49068)
    at Oe.result [as filteredSortedResults] (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/memoize-one/lib/index.js:31:27)
    at Oe.getProps (file:///Applications/Realm%20Studio.app/Contents/Resources/app.asar/build/realm-browser.renderer.bundle.js:1:55429)
    at Oe.render (file:///Applications/Realm%20Studio.app/Contents/Resources/app.asar/build/realm-browser.renderer.bundle.js:1:55265)
    at finishClassComponent (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13085:31)
    at updateClassComponent (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13047:10)
    at beginWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13715:14)
    at performUnitOfWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15741:12)
    at workLoop (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15780:24)
    at renderRoot (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15820:7)
    at performWorkOnRoot (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16437:22)
    at performWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16358:7)
    at performSyncWork (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16330:3)
    at interactiveUpdates$1 (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16597:7)
    at interactiveUpdates (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:2150:10)
    at dispatchInteractiveEvent (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:4528:3)
    at HTMLDocument.wrapped (/Applications/Realm Studio.app/Contents/Resources/app.asar/node_modules/@sentry/electron/node_modules/@sentry/browser/dist/index.js:2471:21)
    in Oe (created by Me)
    in div (created by Me)
    in div (created by Me)
    in Me (created by ze)
    in ze (created by _)
    in _
    in w
```

**Comment by kraenhansen** [comment]
This was fixed with https://github.com/realm/realm-studio/pull/984 released as Realm Studio v3.0.4, please re-open if the issue persists after you've upgraded Studio to the latest version.
